version: '3'

networks:
  n_nginx:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24  ## 宿主机一般会是该网段的 .1，所以不要设置网段为1 

services:
  blog:
    build: ./blog/
    ports:
      - "9000:80"
    restart: always
    volumes:
      - /usr/local/etc/github/woshidasusu.github.io/:/usr/share/nginx/html/:ro
    networks:
      n_nginx:
        ipv4_address: 192.168.5.105
  jenkins:
    build: ./jenkins/
    ports:
      - "9001:8080"
      - "50000:50000"
    user: root
    restart: always
    volumes:
      - /usr/local/etc/github/woshidasusu.github.io/:/var/jenkins_home/blog/codes/
      - /root/.ssh/:/root/.ssh/:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      n_nginx:
        ipv4_address: 192.168.5.104
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    restart: always
    networks:
      n_nginx:
        ipv4_address: 192.168.5.103

