version: '3'

services:
  blog:
    build: ./blog/
    ports:
      - "9000:80"
    restart: always
    volumes:
      - /usr/local/etc/github/woshidasusu.github.io/:/usr/share/nginx/html/:ro
    networks:
      n_nginx:
        ipv4_address: 192.168.5.105
  gitbook:
    build: ./gitbook/
    ports:
      - "9002:80"
    restart: always
    volumes:
      - /usr/local/etc/docker/gitbook/html/:/usr/share/nginx/html/
    networks:
      n_nginx:
        ipv4_address: 192.168.5.106
  jenkins:
    build: ./jenkins/
    ports:
      - "9001:8080"
      - "50000:50000"
    user: root
    restart: always
    volumes:
      - /usr/local/etc/github/woshidasusu.github.io/:/var/jenkins_home/blog/codes/
      - /usr/local/etc/github/Doc/:/var/jenkins_home/gitbook/codes/
      - /root/.ssh/:/root/.ssh/:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      n_nginx:
        ipv4_address: 192.168.5.104
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    restart: always
    networks:
      n_nginx:
        ipv4_address: 192.168.5.103
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=147zaqXSW!
      - POSTGRES_USER=postgres
    volumes:
      - /usr/local/etc/postgres/data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      n_nginx:
        ipv4_address: 192.168.5.107
  nextcloud:
    image: nextcloud
    ports:
      - 9003:80
    volumes:
      - nextcloud:/var/www/html
    networks:
      n_nginx:
        ipv4_address: 192.168.5.108  

networks:
  n_nginx:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24  ## 宿主机一般会是该网段的 .1，所以不要设置网段为1 i

volumes:
  nextcloud:
